name: OC Lettings GL

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Linting
        run: |
          source venv/bin/activate
          flake8 --ignore=E501

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest --cov=.

  containerize:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/oc_lettings_site:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/oc_lettings_site:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: containerize
    steps:
      - name: Deploy to Render
        run: |
          curl -fsSL https://cli.render.com/install.sh | bash
          render login --api-key ${{ secrets.RENDER_API_KEY }}
          render deploy --service OC_Lettings --docker-image ${{ secrets.DOCKER_USERNAME }}/oc_lettings_site:${{ github.sha }}
